# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Buscador.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(528, 708)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titol_2 = QtWidgets.QLabel(self.centralwidget)
        self.Titol_2.setGeometry(QtCore.QRect(30, 20, 469, 89))
        self.Titol_2.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
"background-color: rgb(255, 170, 0);")
        self.Titol_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Titol_2.setObjectName("Titol_2")
        self.Txt_Buscar = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_Buscar.setGeometry(QtCore.QRect(30, 120, 391, 21))
        self.Txt_Buscar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Txt_Buscar.setObjectName("Txt_Buscar")
        self.Btn_Buscar = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Buscar.setGeometry(QtCore.QRect(420, 120, 75, 23))
        self.Btn_Buscar.setStyleSheet("background-color: rgb(170, 170, 166);\n"
"font: 87 10pt \"Arial Black\";")
        self.Btn_Buscar.setObjectName("Btn_Buscar")
        self.Txt_Buscado = QtWidgets.QLabel(self.centralwidget)
        self.Txt_Buscado.setGeometry(QtCore.QRect(30, 150, 461, 501))
        self.Txt_Buscado.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.Txt_Buscado.setText("")
        self.Txt_Buscado.setObjectName("Txt_Buscado")
        self.Enrere = QtWidgets.QPushButton(self.centralwidget)
        self.Enrere.setGeometry(QtCore.QRect(130, 660, 261, 31))
        self.Enrere.setStyleSheet("background-color: rgb(109, 109, 109);\n"
"font: 87 14pt \"Arial Black\";")
        self.Enrere.setText("")
        self.Enrere.setObjectName("Enrere")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titol_2.setText(_translate("MainWindow", "Buscador"))
        self.Txt_Buscar.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Btn_Buscar.setText(_translate("MainWindow", "Buscar"))
        self.Enrere.setText(_translate("MainWindow", "Enrere"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
